language: python
python:
  - "3.5"

notifications:
  email: false

install:
  - pip install smeftrunner
  - pip install coveralls

script: nosetests --with-coverage --cover-package=smeftrunner

after_success: coveralls
