language: python
python:
  - "3.5"
  - "3.6"

notifications:
  email: false

install:
  - pip install -e .
  - pip install coveralls

script: nosetests --with-coverage --cover-package=smeftrunner

after_success: coveralls
